version: "3.12"
services:
  app:
    build: .
    volumes:
      - .:/home/OtelApp
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres