# Generated by Django 4.2.6 on 2023-10-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtelOda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odaNumarasi', models.CharField(max_length=5, verbose_name='Oda Numarası')),
                ('odaTipi', models.CharField(max_length=50, verbose_name='Oda Tipi')),
                ('odaFiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Oda Fiyatı')),
                ('odaTemizMi', models.BooleanField(blank=True, default=True, verbose_name='Oda Temiz Mi?')),
                ('odaArizaliMi', models.BooleanField(blank=True, default=False, verbose_name='Oda Arızalı Mı?')),
                ('odaBosMu', models.BooleanField(blank=True, default=False, verbose_name='Oda Boş Mu?')),
                ('odaProblemi', models.TextField(max_length=500, verbose_name='Odanın Problemi Nedir?')),
                ('otel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelIcerik.otelyonetim', verbose_name='Otel Adı')),
            ],
        ),
    ]
