# Generated by Django 4.2.6 on 2023-10-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0002_oteloda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oteloda',
            name='odaProblemi',
            field=models.TextField(blank=True, max_length=500, verbose_name='Odanın Problemi Nedir?'),
        ),
    ]
