# Generated by Django 4.2.6 on 2023-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0004_oteloda_odarezervemi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oteloda',
            name='odaBosMu',
            field=models.BooleanField(blank=True, default=True, verbose_name='Oda Boş Mu?'),
        ),
    ]
