# Generated by Django 4.2.6 on 2023-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0005_alter_oteloda_odabosmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oteloda',
            name='odaFiyat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Oda Fiyatı'),
        ),
    ]
