# Generated by Django 4.2.6 on 2023-10-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0006_alter_oteloda_odafiyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonukBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Müşterinin Adı')),
                ('lastname', models.CharField(max_length=50, verbose_name='Müşterinin Soyadı')),
                ('uyrugu', models.CharField(max_length=50, verbose_name='Müşterinin Uyruğu')),
                ('musteriTC', models.CharField(blank=True, max_length=11, verbose_name='Müşteri TC Numarası')),
                ('musteriID', models.CharField(blank=True, max_length=50, verbose_name='Müşteri Passaport Numarası')),
                ('musteriNotu', models.CharField(max_length=50, verbose_name='Müşteri Notu')),
                ('otel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OtelIcerik.otelyonetim', verbose_name='Otel Adı')),
            ],
        ),
    ]
