# Generated by Django 4.2.6 on 2023-10-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0008_konukcheckinvecheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oteloda',
            name='odaFiyat',
        ),
    ]
