# Generated by Django 4.2.6 on 2023-10-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0010_alter_konukbilgileri_musterinotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='musteriNotu',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Müşteri Notu'),
        ),
    ]
