# Generated by Django 4.2.6 on 2023-10-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0011_alter_konukbilgileri_musterinotu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konukcheckinvecheckout',
            options={'verbose_name': 'CheckInCheckOut', 'verbose_name_plural': 'CheckInCheckOut'},
        ),
    ]
