# Generated by Django 4.2.6 on 2023-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0013_alter_konukbilgileri_options_alter_oteloda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konukcheckinvecheckout',
            name='fiyat',
        ),
        migrations.AddField(
            model_name='konukbilgileri',
            name='fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat'),
        ),
    ]
