# Generated by Django 4.2.5 on 2023-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0014_remove_konukcheckinvecheckout_fiyat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konukbilgileri',
            name='kur',
            field=models.CharField(blank=True, default='TRY', max_length=50, verbose_name='Para Birimi'),
        ),
    ]
