# Generated by Django 4.2.5 on 2023-11-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0016_konukbilgileri_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konukbilgileri',
            name='birthday',
            field=models.CharField(max_length=50, verbose_name='Müşteri Doğum Tarihi'),
        ),
    ]
