# Generated by Django 4.2.5 on 2023-11-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0018_konukcheckinvecheckout_eventcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konukcheckinvecheckout',
            old_name='eventColor',
            new_name='color',
        ),
    ]
