# Generated by Django 4.2.5 on 2023-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0019_rename_eventcolor_konukcheckinvecheckout_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='oteloda',
            name='odaBlokajliMi',
            field=models.BooleanField(blank=True, default=False, verbose_name='Oda Blokajlı Mı?'),
        ),
    ]
