# Generated by Django 4.2.5 on 2023-11-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0020_oteloda_odablokajlimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oteloda',
            name='odaBlokajliMi',
        ),
    ]
