# Generated by Django 4.2.5 on 2023-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtelIcerik', '0021_remove_oteloda_odablokajlimi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otelyonetim',
            name='image',
            field=models.ImageField(blank=True, upload_to='Logo', verbose_name='Otel Logosu'),
        ),
    ]
